### ISSUE TITLE
Developer Feedback

### ISSUE THREAD

**Issue by heysupratim** [leavjenn/Hews#1]
Hey just saw your post in HN , i am a developer for Cloudmagic the android app and i have been looking for collaborating on some young projects . Too much of contrib activity goes on for bigger projects , I was thinking of helping here . 

Tell me what could be done next and whats in your mind for this app ? Well the icon sure does look a little out of the place, i will look into taking to a designer at my place and get some help in making the icon , till then what else ?

**Comment by heysupratim** [comment]
@leavjenn  - much ignore sir :P

**Comment by leavjenn** [comment]
@borax12 Ah, so sorry for that. I have seen your feedback, and in fact, at that time I didn't really figure out what's next to improve, so I didn't reply. Sorry again. For now I'm adding login and related feature, next...well I still don't know:) 

The more important thing that confused me is why this app gets so few downloads. I donn't know what's wrong with it. Icon? UI? Lack of some critical feature besides login? Some nasty bugs? With that sparse user base, I've got almost no feedback. I think that's the most important part: I don't know what users thought of it. So after adding login feature, I'll try to get some exposure and see what users want.

Thank you for still remember this issue:)

**Comment by heysupratim** [comment]
Well see there is one thing that people get wrong related to software products that is functional design, i can probably help you get around that , i am trained product manager . I do product management for startups . But for you i get help get your design issues sorted  ;)
